version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: fitness_postgres
    environment:
      POSTGRES_DB: fitness_db
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: fitness_app
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fitness_db
#      SPRING_DATASOURCE_USERNAME: fitness_user
#      SPRING_DATASOURCE_PASSWORD: fitness_pass
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:
