name: Build and push

on:
  pull_request:
    branches: [ master ]


env:
  TF_VERSION: "1.1.0"
  AWS_REGION: "eu-west-2"

jobs:
  fitness-tracker:
    if: "!contains(github.event.commits[0].message, '[Bump version to]')"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build artefact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ~/.m2/settings.xml
          mvn clean install

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/statement2020/fitness-tracker:1.0.${{github.run_number}},ghcr.io/statement2020/fitness-tracker:latest
